routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'WebController@index')->name('home.index');

Route::get('/search-job', 'WebController@searchJob')->name('searchJob.index');
Route::post('/search-job/search', 'WebController@searchcat')->name('searchcat.index');

Route::get('/find-a-candidate', function () {
    return view('findCandidate.index');
})->name('findCandidate.index');

Route::get('/register', function () {
    return view('auth.register');
})->name('user.reg');

Route::get('/about-us', 'WebController@aboutUs')->name('aboutUsWeb.index');

Route::get('/shop', function () {
    return view('shop.index');
})->name('shop.index');

Route::get('/companies', 'WebController@companies')->name('companies.index');

Route::get('/pricings', 'WebController@pricing')->name('pricings.index');

Route::get('/blog', function () {
    return view('blog.index');
})->name('blog.index');

Route::get('/faq', 'WebController@faq')->name('webFaq.index');

Route::get('/privacy-policy', 'WebController@privacypolicy')->name('privacyPolicy.index');

Route::get('/job/{id}', 'JobController@show')->name('job.show');
Route::get('/company/{id}', 'CompanyController@show')->name('company.show');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');

});

// routing manager
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth' => 'dashboard']], function () {

    Route::get('/home', function () {
        return view('dashboard.home.index');
    })->name('dashboard.home.index');

    Route::resource('sliders', 'SliderController');
    Route::resource('category', 'CategoryController');
    Route::get('category/{id}/statusUpdate', 'CategoryController@statusUpdate')->name('category.statusUpdate');
    Route::resource('faq', 'FaqController');
    Route::resource('aboutUs', 'AboutUsController');
    Route::resource('pricing', 'PricingController');
    Route::resource('privacyPolice', 'PrivacyPolicyController');
    Route::resource('resume', 'ResumeController');
    Route::get('/candidate', 'CandidateController@index')->name('candidate.index');
    Route::get('/candidate/{id}/show', 'CandidateController@show')->name('candidate.show');
    Route::get('/company', 'CompanyController@index')->name('company.index');
    Route::get('/company/{id}/showProfile', 'CompanyController@showProfile')->name('company.showProfile');
    Route::get('/order', 'OrderController@index')->name('order.index');
    Route::get('/order/{id}/show', 'OrderController@show')->name('order.show');
    Route::get('/order/{id}/accept', 'OrderController@accept')->name('order.accept');
    Route::get('/order/{id}/cancel', 'OrderController@cancel')->name('order.cancel');

    Route::get('/resume', 'ResumeController@indexDashboard')->name('resume.indexDashboard');
    Route::get('/resume/show/{id}', 'ResumeController@showDashboard')->name('resume.showDashboard');

    Route::get('/jobs', 'JobController@index')->name('jobs.index');
    Route::get('/jobs/{id}/recUpdateJob', 'JobController@recUpdateJob')->name('dashboard.jobs.recUpdateJob');
    Route::post('/jobs/{id}/destroy', 'JobController@destroyDashboard')->name('dashboard.jobs.destroy');

});

// routing company
Route::group(['prefix' => 'company', 'middleware' => ['auth' => 'company']], function () {

//    Route::get('/advertisement/create', 'AdvertController@create')->name('advert.create');

    Route::get('/profile/create', 'CompanyController@create')->name('profile.create');
    Route::post('/profile/store', 'CompanyController@store')->name('profile.store');
    Route::get('/profile/{id}/edit', 'CompanyController@edit')->name('profile.edit');
    Route::post('/profile/{id}/update', 'CompanyController@update')->name('profile.update');
    Route::get('/profile/{id}', 'CompanyController@show')->name('profile.show');

    Route::get('/post-job/create', 'JobController@create')->name('job.create');
    Route::post('/post-job/store', 'JobController@store')->name('job.store');
    Route::get('/job/{id}/edit', 'JobController@edit')->name('job.edit');
    Route::post('/job/{id}/update', 'JobController@update')->name('job.update');
    Route::post('/job/{id}/destroy', 'JobController@destroy')->name('job.destroy');
    Route::get('/job/list-applicant/{id}', 'JobController@listCandidate')->name('job.listCandidate');
    Route::get('applicant/profile/{id}', 'CandidateController@candidateProfile')->name('applicant.profile.show');

    // Route::get('/post_job', function () {
    //     return view('job.create');
    // })->name('job.create');

    Route::get('/pricings/checkout', 'PricingController@checkout')->name('pricing.checkout');
    Route::post('/pricings/checkout/store', 'OrderController@store')->name('order.pricingStore');
    Route::post('/pricings/paymentconfirmation/store', 'PaymentConfirmationController@store')->name('paymentconfirm.store');

});

// routing trainer
Route::group(['prefix' => 'trainer', 'middleware' => ['auth' => 'trainer']], function () {

});

// routing user
Route::group(['prefix' => 'user', 'middleware' => ['auth' => 'user']], function () {

    Route::get('/profile/create', 'CandidateController@create')->name('candidate.profile.create');
    Route::post('/profile/store', 'CandidateController@store')->name('candidate.profile.store');
    Route::get('/profile/{id}', 'CandidateController@candidateProfile')->name('candidate.profile.show');
    Route::get('/profile/{id}/edit', 'CandidateController@edit')->name('candidate.profile.edit');
    Route::post('/profile/{id}/update', 'CandidateController@update')->name('candidate.profile.update');

    Route::get('/resume', 'ResumeController@index')->name('resume.index');
    Route::post('/resume/store', 'ResumeController@store')->name('resume.store');
    Route::post('/resume/{id}/update', 'ResumeController@update')->name('resume.update');

    Route::post('/apply/store', 'JobApplicantController@store')->name('apply.store');

});

app/Models/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    protected $fillable = [
        'title',
        'subtitle',
        'image',
        'rowPointer'
    ];
}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use App\Slider;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Ramsey\Uuid\Uuid;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders = Slider::get();

        return view('dashboard.slider.index', ['sliders' => $sliders]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'subtitle' => 'required',
            'image' => 'mimes:jpeg,jpg,png|required|max:40000',
        ]);

        $imageName = time() . '.' . request()->image->getClientOriginalExtension();

        request()->image->move(public_path() . '/upload/sliders/', $imageName);

        Slider::insert([
            'title' => $request->title,
            'subtitle' => $request->subtitle,
            'image' => $imageName,
            'rowPointer' => Uuid::uuid4()->getHex(),
            'created_at' => Carbon::now()
        ]);

        return redirect()->route('sliders.index')->with('success','Slider created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function show(Slider $slider)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function edit(Slider $slider)
    {
        return view('dashboard.slider.edit', ['slider' => $slider]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Slider $slider)
    {
        $request->validate([
            'title' => 'required',
            'subtitle' => 'required',
        ]);

        if ($request->image == null) {

            $imageName = $slider->image;

        } else {

            $imageName = time() . '.' . request()->image->getClientOriginalExtension();

            request()->image->move(public_path() . '/upload/sliders/', $imageName);

        }

        $slider->update([
            'title' => $request->title,
            'subtitle' => $request->subtitle,
            'image' => $imageName,
            'updated_at' => Carbon::now()
        ]);

        return redirect()->route('sliders.index')->with('success','Slider updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slider $slider)
    {
        $slider->delete();

        return redirect()->route('sliders.index')->with('success','Slider deleted successfully.');
    }
}

resources/views/dashboard/slider/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <div class="section-header-back">
                    <a href="features-posts.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
                </div>
                <h1>Create New Slider</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Slider</a></div>
                    <div class="breadcrumb-item">Create New Slider</div>
                </div>
            </div>

            <div class="section-body">

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <h2 class="section-title">Create New Slider</h2>
                <p class="section-lead">
                    On this page you can create a new slider and fill in all fields.
                </p>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Create Your Slider</h4>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('sliders.store') }}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" class="form-control" name="title">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Subtitle</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" class="form-control" name="subtitle">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image Slider</label>
                                        <div class="col-sm-12 col-md-7">
                                            <div id="image-preview" class="image-preview" style="width: 500px;">
                                                <label for="image-upload" id="image-label">Choose File</label>
                                                <input type="file" name="image" id="image-upload" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">Create Slider</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop

resources/views/dashboard/slider/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <div class="section-header-back">
                    <a href="features-posts.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
                </div>
                <h1>Update Slider</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Slider</a></div>
                    <div class="breadcrumb-item">Update Slider</div>
                </div>
            </div>

            <div class="section-body">

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <h2 class="section-title">Update Slider</h2>
                <p class="section-lead">
                    On this page you can update slider and fill in all fields.
                </p>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Update Your Slider</h4>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('sliders.update', $slider->id) }}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" class="form-control" name="title" value="{{ $slider->title }}">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Subtitle</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" class="form-control" name="subtitle" value="{{ $slider->subtitle }}">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image Slider</label>
                                        <div class="col-sm-12 col-md-7">
                                            <div id="image-preview" class="image-preview" style="width: 500px; background-image: url({{ asset('upload/sliders/'. $slider->image) }}); background-size: cover; background-position: center center;">
                                                <label for="image-upload" id="image-label">Change Image</label>
                                                <input type="file" name="image" id="image-upload" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">Update Slider</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop

resources/views/dashboard/slider/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Slider</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Slider</a></div>
{{--                    <div class="breadcrumb-item">DataTables</div>--}}
                </div>
            </div>

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <div class="section-body">
                <h2 class="section-title">Slider
                    <div class="float-right">
                        <a href="{{ route('sliders.create') }}" class="btn btn-primary">Create Slider</a>
                    </div>
                </h2>
                <p class="section-lead">
                    Slider will be display on the top of the website index
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Slider</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-1">
                                        <thead>
                                        <tr>
                                            <th class="text-center" width="8%">
                                                #
                                            </th>
                                            <th>Title</th>
                                            <th width="50%">Subtitle</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($sliders as $index => $slider)
                                                <tr>
                                                    <td class="text-center">{{ $index+1 }}</td>
                                                    <td>{{ $slider->title }}</td>
                                                    <td>{{ $slider->subtitle }}</td>
                                                    <td><img src="{{ asset('upload/sliders/'. $slider->image) }}" alt="" style="width: 100%; max-width: 100px; height: auto;"></td>
                                                    <td>
                                                        <form action="{{ route('sliders.destroy', $slider->id) }}" method="post">
                                                            <a href="{{ route('sliders.edit', $slider->id) }}" class="btn btn-warning">Edit</a>

                                                            @csrf
                                                            @method('DELETE')

                                                            <button type="submit" class="btn btn-danger">Delete</button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop