routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'WebController@index')->name('home.index');

Route::get('/search-job', 'WebController@searchJob')->name('searchJob.index');
Route::post('/search-job/search', 'WebController@searchcat')->name('searchcat.index');

Route::get('/find-a-candidate', function () {
    return view('findCandidate.index');
})->name('findCandidate.index');

Route::get('/register', function () {
    return view('auth.register');
})->name('user.reg');

Route::get('/about-us', 'WebController@aboutUs')->name('aboutUsWeb.index');

Route::get('/shop', function () {
    return view('shop.index');
})->name('shop.index');

Route::get('/companies', 'WebController@companies')->name('companies.index');

Route::get('/pricings', 'WebController@pricing')->name('pricings.index');

Route::get('/blog', function () {
    return view('blog.index');
})->name('blog.index');

Route::get('/faq', 'WebController@faq')->name('webFaq.index');

Route::get('/privacy-policy', 'WebController@privacypolicy')->name('privacyPolicy.index');

Route::get('/job/{id}', 'JobController@show')->name('job.show');
Route::get('/company/{id}', 'CompanyController@show')->name('company.show');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');

});

// routing manager
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth' => 'dashboard']], function () {

    Route::get('/home', function () {
        return view('dashboard.home.index');
    })->name('dashboard.home.index');

    Route::resource('sliders', 'SliderController');
    Route::resource('category', 'CategoryController');
    Route::get('category/{id}/statusUpdate', 'CategoryController@statusUpdate')->name('category.statusUpdate');
    Route::resource('faq', 'FaqController');
    Route::resource('aboutUs', 'AboutUsController');
    Route::resource('pricing', 'PricingController');
    Route::resource('privacyPolice', 'PrivacyPolicyController');
    Route::resource('resume', 'ResumeController');
    Route::get('/candidate', 'CandidateController@index')->name('candidate.index');
    Route::get('/candidate/{id}/show', 'CandidateController@show')->name('candidate.show');
    Route::get('/company', 'CompanyController@index')->name('company.index');
    Route::get('/company/{id}/showProfile', 'CompanyController@showProfile')->name('company.showProfile');
    Route::get('/order', 'OrderController@index')->name('order.index');
    Route::get('/order/{id}/show', 'OrderController@show')->name('order.show');
    Route::get('/order/{id}/accept', 'OrderController@accept')->name('order.accept');
    Route::get('/order/{id}/cancel', 'OrderController@cancel')->name('order.cancel');

    Route::get('/resume', 'ResumeController@indexDashboard')->name('resume.indexDashboard');
    Route::get('/resume/show/{id}', 'ResumeController@showDashboard')->name('resume.showDashboard');

    Route::get('/jobs', 'JobController@index')->name('jobs.index');
    Route::get('/jobs/{id}/recUpdateJob', 'JobController@recUpdateJob')->name('dashboard.jobs.recUpdateJob');
    Route::post('/jobs/{id}/destroy', 'JobController@destroyDashboard')->name('dashboard.jobs.destroy');

});

// routing company
Route::group(['prefix' => 'company', 'middleware' => ['auth' => 'company']], function () {

//    Route::get('/advertisement/create', 'AdvertController@create')->name('advert.create');

    Route::get('/profile/create', 'CompanyController@create')->name('profile.create');
    Route::post('/profile/store', 'CompanyController@store')->name('profile.store');
    Route::get('/profile/{id}/edit', 'CompanyController@edit')->name('profile.edit');
    Route::post('/profile/{id}/update', 'CompanyController@update')->name('profile.update');
    Route::get('/profile/{id}', 'CompanyController@show')->name('profile.show');

    Route::get('/post-job/create', 'JobController@create')->name('job.create');
    Route::post('/post-job/store', 'JobController@store')->name('job.store');
    Route::get('/job/{id}/edit', 'JobController@edit')->name('job.edit');
    Route::post('/job/{id}/update', 'JobController@update')->name('job.update');
    Route::post('/job/{id}/destroy', 'JobController@destroy')->name('job.destroy');
    Route::get('/job/list-applicant/{id}', 'JobController@listCandidate')->name('job.listCandidate');
    Route::get('applicant/profile/{id}', 'CandidateController@candidateProfile')->name('applicant.profile.show');

    // Route::get('/post_job', function () {
    //     return view('job.create');
    // })->name('job.create');

    Route::get('/pricings/checkout', 'PricingController@checkout')->name('pricing.checkout');
    Route::post('/pricings/checkout/store', 'OrderController@store')->name('order.pricingStore');
    Route::post('/pricings/paymentconfirmation/store', 'PaymentConfirmationController@store')->name('paymentconfirm.store');

});

// routing trainer
Route::group(['prefix' => 'trainer', 'middleware' => ['auth' => 'trainer']], function () {

});

// routing user
Route::group(['prefix' => 'user', 'middleware' => ['auth' => 'user']], function () {

    Route::get('/profile/create', 'CandidateController@create')->name('candidate.profile.create');
    Route::post('/profile/store', 'CandidateController@store')->name('candidate.profile.store');
    Route::get('/profile/{id}', 'CandidateController@candidateProfile')->name('candidate.profile.show');
    Route::get('/profile/{id}/edit', 'CandidateController@edit')->name('candidate.profile.edit');
    Route::post('/profile/{id}/update', 'CandidateController@update')->name('candidate.profile.update');

    Route::get('/resume', 'ResumeController@index')->name('resume.index');
    Route::post('/resume/store', 'ResumeController@store')->name('resume.store');
    Route::post('/resume/{id}/update', 'ResumeController@update')->name('resume.update');

    Route::post('/apply/store', 'JobApplicantController@store')->name('apply.store');

});

resources/views/dashboard/privacyPolice/create.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
          <a href="features-posts.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Create Privacy Policy Content</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Privacy Policy</a></div>
          <div class="breadcrumb-item">Create Privacy Policy Content</div>
        </div>
      </div>

      <div class="section-body">
        <h2 class="section-title">Create Privacy Policy Content</h2>
        <p class="section-lead">
          On this page you can create a privacy policy content and fill in all fields.
        </p>

        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Write Your Content</h4>
              </div>
              <div class="card-body">
                  <form action="{{ route('privacyPolice.store') }}" method="post">
                      @csrf
                      <div class="form-group row mb-4">
                          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                          <div class="col-sm-12 col-md-7">
                              <input type="text" class="form-control" value="Privacy Policy" readonly>
                          </div>
                      </div>
                      <div class="form-group row mb-4">
                          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                          <div class="col-sm-12 col-md-7">
                              <textarea class="summernote-simple" name="text"></textarea>
                          </div>
                      </div>
                      <div class="form-group row mb-4">
                          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Location</label>
                          <div class="col-sm-12 col-md-7">
                              <input type="text" class="form-control" name="location">
                          </div>
                      </div>
                      <div class="form-group row mb-4">
                          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Phone</label>
                          <div class="col-sm-12 col-md-7">
                              <input type="number" class="form-control" name="phone">
                          </div>
                      </div>
                      <div class="form-group row mb-4">
                          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                          <div class="col-sm-12 col-md-7">
                              <button class="btn btn-primary">Create Content</button>
                          </div>
                      </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@stop

resources/views/dashboard/privacyPolice/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <div class="section-header-back">
                    <a href="features-posts.html" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
                </div>
                <h1>Edit Privacy Policy Content</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Privacy Policy</a></div>
                    <div class="breadcrumb-item">Edit Privacy Policy Content</div>
                </div>
            </div>

            <div class="section-body">
                <h2 class="section-title">Edit Privacy Policy Content</h2>
                <p class="section-lead">
                    On this page you can update a privacy policy content and fill in all fields.
                </p>

                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Write Your Content</h4>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('privacyPolice.update', $privacypolice->id) }}" method="post">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Title</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" class="form-control" value="Privacy Policy" readonly>
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                                        <div class="col-sm-12 col-md-7">
                                            <textarea class="summernote-simple" name="text">{{ $privacypolice->text }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Location</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" class="form-control" name="location" value="{{ $privacypolice->location }}">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Phone</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="number" class="form-control" name="phone" value="{{ $privacypolice->phone }}">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">Update Content</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop

resources/views/dashboard/privacyPolice/index.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Privacy Policy Content</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
                    <div class="breadcrumb-item"><a href="#">Privacy Policy Content</a></div>
                    {{--                    <div class="breadcrumb-item">DataTables</div>--}}
                </div>
            </div>

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <div class="section-body">
                <h2 class="section-title">Privacy Policy Content
                    <div class="float-right">
                        <a href="{{ route('privacyPolice.create') }}" class="btn btn-primary">Create Privacy Policy Content</a>
                    </div>
                </h2>
                <p class="section-lead">
                    Privacy Policy Content will be display on the privacy police page
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Privacy Policy Content</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-1">
                                        <thead>
                                        <tr>
                                            <th class="text-center" width="8%">
                                                #
                                            </th>
                                            <th>Content</th>
                                            <th>Location</th>
                                            <th>Phone</th>
                                            <th width="20%">Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($privacypolices as $index => $privacypolice)
                                            <tr>
                                                <td class="text-center">{{ $index+1 }}</td>
                                                <td>{{ \Illuminate\Support\Str::limit(strip_tags($privacypolice->text), '50', ' ...') }}</td>
                                                <td>{{ $privacypolice->location }}</td>
                                                <td>{{ $privacypolice->phone }}</td>
                                                <td>
                                                    <form action="{{ route('privacyPolice.destroy', $privacypolice->id) }}" method="post">
                                                        <a href="{{ route('privacyPolice.edit', $privacypolice->id) }}" class="btn btn-warning">Edit</a>

                                                        @csrf
                                                        @method('DELETE')

                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@stop