routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'WebController@index')->name('home.index');

Route::get('/search-job', 'WebController@searchJob')->name('searchJob.index');
Route::post('/search-job/search', 'WebController@searchcat')->name('searchcat.index');

Route::get('/find-a-candidate', function () {
    return view('findCandidate.index');
})->name('findCandidate.index');

Route::get('/register', function () {
    return view('auth.register');
})->name('user.reg');

Route::get('/about-us', 'WebController@aboutUs')->name('aboutUsWeb.index');

Route::get('/shop', function () {
    return view('shop.index');
})->name('shop.index');

Route::get('/companies', 'WebController@companies')->name('companies.index');

Route::get('/pricings', 'WebController@pricing')->name('pricings.index');

Route::get('/blog', function () {
    return view('blog.index');
})->name('blog.index');

Route::get('/faq', 'WebController@faq')->name('webFaq.index');

Route::get('/privacy-policy', 'WebController@privacypolicy')->name('privacyPolicy.index');

Route::get('/job/{id}', 'JobController@show')->name('job.show');
Route::get('/company/{id}', 'CompanyController@show')->name('company.show');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');

});

// routing manager
Route::group(['prefix' => 'dashboard', 'middleware' => ['auth' => 'dashboard']], function () {

    Route::get('/home', function () {
        return view('dashboard.home.index');
    })->name('dashboard.home.index');

    Route::resource('sliders', 'SliderController');
    Route::resource('category', 'CategoryController');
    Route::get('category/{id}/statusUpdate', 'CategoryController@statusUpdate')->name('category.statusUpdate');
    Route::resource('faq', 'FaqController');
    Route::resource('aboutUs', 'AboutUsController');
    Route::resource('pricing', 'PricingController');
    Route::resource('privacyPolice', 'PrivacyPolicyController');
    Route::resource('resume', 'ResumeController');
    Route::get('/candidate', 'CandidateController@index')->name('candidate.index');
    Route::get('/candidate/{id}/show', 'CandidateController@show')->name('candidate.show');
    Route::get('/company', 'CompanyController@index')->name('company.index');
    Route::get('/company/{id}/showProfile', 'CompanyController@showProfile')->name('company.showProfile');
    Route::get('/order', 'OrderController@index')->name('order.index');
    Route::get('/order/{id}/show', 'OrderController@show')->name('order.show');
    Route::get('/order/{id}/accept', 'OrderController@accept')->name('order.accept');
    Route::get('/order/{id}/cancel', 'OrderController@cancel')->name('order.cancel');

    Route::get('/resume', 'ResumeController@indexDashboard')->name('resume.indexDashboard');
    Route::get('/resume/show/{id}', 'ResumeController@showDashboard')->name('resume.showDashboard');

    Route::get('/jobs', 'JobController@index')->name('jobs.index');
    Route::get('/jobs/{id}/recUpdateJob', 'JobController@recUpdateJob')->name('dashboard.jobs.recUpdateJob');
    Route::post('/jobs/{id}/destroy', 'JobController@destroyDashboard')->name('dashboard.jobs.destroy');

});

// routing company
Route::group(['prefix' => 'company', 'middleware' => ['auth' => 'company']], function () {

//    Route::get('/advertisement/create', 'AdvertController@create')->name('advert.create');

    Route::get('/profile/create', 'CompanyController@create')->name('profile.create');
    Route::post('/profile/store', 'CompanyController@store')->name('profile.store');
    Route::get('/profile/{id}/edit', 'CompanyController@edit')->name('profile.edit');
    Route::post('/profile/{id}/update', 'CompanyController@update')->name('profile.update');
    Route::get('/profile/{id}', 'CompanyController@show')->name('profile.show');

    Route::get('/post-job/create', 'JobController@create')->name('job.create');
    Route::post('/post-job/store', 'JobController@store')->name('job.store');
    Route::get('/job/{id}/edit', 'JobController@edit')->name('job.edit');
    Route::post('/job/{id}/update', 'JobController@update')->name('job.update');
    Route::post('/job/{id}/destroy', 'JobController@destroy')->name('job.destroy');
    Route::get('/job/list-applicant/{id}', 'JobController@listCandidate')->name('job.listCandidate');
    Route::get('applicant/profile/{id}', 'CandidateController@candidateProfile')->name('applicant.profile.show');

    // Route::get('/post_job', function () {
    //     return view('job.create');
    // })->name('job.create');

    Route::get('/pricings/checkout', 'PricingController@checkout')->name('pricing.checkout');
    Route::post('/pricings/checkout/store', 'OrderController@store')->name('order.pricingStore');
    Route::post('/pricings/paymentconfirmation/store', 'PaymentConfirmationController@store')->name('paymentconfirm.store');

});

// routing trainer
Route::group(['prefix' => 'trainer', 'middleware' => ['auth' => 'trainer']], function () {

});

// routing user
Route::group(['prefix' => 'user', 'middleware' => ['auth' => 'user']], function () {

    Route::get('/profile/create', 'CandidateController@create')->name('candidate.profile.create');
    Route::post('/profile/store', 'CandidateController@store')->name('candidate.profile.store');
    Route::get('/profile/{id}', 'CandidateController@candidateProfile')->name('candidate.profile.show');
    Route::get('/profile/{id}/edit', 'CandidateController@edit')->name('candidate.profile.edit');
    Route::post('/profile/{id}/update', 'CandidateController@update')->name('candidate.profile.update');

    Route::get('/resume', 'ResumeController@index')->name('resume.index');
    Route::post('/resume/store', 'ResumeController@store')->name('resume.store');
    Route::post('/resume/{id}/update', 'ResumeController@update')->name('resume.update');

    Route::post('/apply/store', 'JobApplicantController@store')->name('apply.store');

});

resources/views/partials/dashboard/_footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2020 <div class="bullet"></div> Develope By <a href="https://nauval.in/">MyGoodnews</a>
    </div>
    <div class="footer-right">
        1.1.0
    </div>
</footer>

resources/views/partials/dashboard/_head.blade.php
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Dashboard &mdash; Simplyyours</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ asset('dashboard/modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dashboard/modules/datatables.net-select-bs4/css/select.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('dashboard/modules/summernote/dist/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('dashboard/modules/selectric/public/selectric.css') }}">
    <link rel="stylesheet" href="{{ asset('dashboard/modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') }}">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{{ asset('dashboard/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('dashboard/css/components.css') }}">

    @yield('extra_styles')
</head>

resources/views/partials/dashboard/_navbar.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
        </ul>
    </form>
    <ul class="navbar-nav navbar-right">
{{--        <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>--}}
{{--            <div class="dropdown-menu dropdown-list dropdown-menu-right">--}}
{{--                <div class="dropdown-header">Notifications--}}
{{--                    <div class="float-right">--}}
{{--                        <a href="#">Mark All As Read</a>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="dropdown-list-content dropdown-list-icons">--}}
{{--                    <a href="#" class="dropdown-item dropdown-item-unread">--}}
{{--                        <div class="dropdown-item-icon bg-primary text-white">--}}
{{--                            <i class="fas fa-code"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            Template update is available now!--}}
{{--                            <div class="time text-primary">2 Min Ago</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="dropdown-item">--}}
{{--                        <div class="dropdown-item-icon bg-info text-white">--}}
{{--                            <i class="far fa-user"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            <b>You</b> and <b>Dedik Sugiharto</b> are now friends--}}
{{--                            <div class="time">10 Hours Ago</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="dropdown-item">--}}
{{--                        <div class="dropdown-item-icon bg-success text-white">--}}
{{--                            <i class="fas fa-check"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>--}}
{{--                            <div class="time">12 Hours Ago</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="dropdown-item">--}}
{{--                        <div class="dropdown-item-icon bg-danger text-white">--}}
{{--                            <i class="fas fa-exclamation-triangle"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            Low disk space. Let's clean it!--}}
{{--                            <div class="time">17 Hours Ago</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <a href="#" class="dropdown-item">--}}
{{--                        <div class="dropdown-item-icon bg-info text-white">--}}
{{--                            <i class="fas fa-bell"></i>--}}
{{--                        </div>--}}
{{--                        <div class="dropdown-item-desc">--}}
{{--                            Welcome to Stisla template!--}}
{{--                            <div class="time">Yesterday</div>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                </div>--}}
{{--                <div class="dropdown-footer text-center">--}}
{{--                    <a href="#">View All <i class="fas fa-chevron-right"></i></a>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </li>--}}
        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <div class="d-sm-none d-lg-inline-block">Hi, {{ Auth::user()->name }} </div></a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/partials/dashboard/_script.blade.php
<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="{{ asset('dashboard/js/stisla.js') }}"></script>

<script src="{{ asset('dashboard/modules/datatables/media/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('dashboard/modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('dashboard/modules/datatables.net-select-bs4/js/select.bootstrap4.min.js') }}"></script>
<script src="{{ asset('dashboard/modules/summernote/dist/summernote-bs4.js') }}"></script>
<script src="{{ asset('dashboard/modules/selectric/public/jquery.selectric.min.js') }}"></script>
<script src="{{ asset('dashboard/modules/jquery_upload_preview/assets/js/jquery.uploadPreview.min.js') }}"></script>
<script src="{{ asset('dashboard/modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js') }}"></script>

<!-- Template JS File -->
<script src="{{ asset('dashboard/js/scripts.js') }}"></script>
<script src="{{ asset('dashboard/js/custom.js') }}"></script>

<!-- Page Specific JS File -->
<script src="{{ asset('dashboard/js/page/index.js') }}"></script>
<script src="{{ asset('dashboard/js/page/modules-datatables.js') }}"></script>
<script src="{{ asset('dashboard/js/page/features-post-create.js') }}"></script>
<script src="{{ asset('dashboard/js/page/bootstrap-modal.js') }}"></script>
@yield('extra_scripts')

resources/views/partials/dashboard/_sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="index.html">Simplyyours</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">CR</a>
        </div>
        <ul class="sidebar-menu">
            <li><a class="nav-link" href="#"><i class="fas fa-fire"></i><span>Dashboard</span></a></li>
            <li><a class="nav-link" href="{{ route('order.index') }}"><i class="fab fa-first-order-alt"></i><span>Order</span></a></li>
            <li class="menu-header">Management Web</li>
            <li><a class="nav-link" href="{{ route('sliders.index') }}"><i class="fas fa-columns"></i><span>Slider</span></a></li>
            <li><a class="nav-link" href="{{ route('category.index') }}"><i class="fas fa-ellipsis-h"></i><span>Category</span></a></li>
            <li><a class="nav-link" href="{{ route('pricing.index') }}"><i class="fas fa-money-check-alt"></i><span>Pricing</span></a></li>
            <li><a class="nav-link" href="{{ route('aboutUs.index') }}"><i class="fas fa-users"></i><span>About Us Content</span></a></li>
            <li><a class="nav-link" href="{{ route('faq.index') }}"><i class="fas fa-tasks"></i><span>Faq Content</span></a></li>
            <li><a class="nav-link" href="{{ route('privacyPolice.index') }}"><i class="fas fa-lock"></i><span>Privacy Policy Content</span></a></li>
            <li class="menu-header">Management User</li>
            <li><a class="nav-link" href="{{ route('candidate.index') }}"><i class="fas fa-user"></i><span>Candidates</span></a></li>
            <li><a class="nav-link" href="{{ route('resume.indexDashboard') }}"><i class="fas fa-file"></i><span>Resume Candidate</span></a></li>
            <li><a class="nav-link" href="{{ route('company.index') }}"><i class="fas fa-building"></i><span>Companies</span></a></li>
            <li><a class="nav-link" href="{{ route('jobs.index') }}"><i class="fab fa-black-tie"></i><span>Jobs</span></a></li>
        </ul>

        <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
            <a href="{{ route('home.index') }}" class="btn btn-primary btn-lg btn-block btn-icon-split">
                <i class="fas fa-rocket"></i> Go to Website
            </a>
        </div>
    </aside>
</div>